// @ts-nocheck — line-for-line port of the untyped design mock; see design_handoff_aidress_website.
// machineText() from design_handoff_aidress_website/design/ui_kits/website/SiteApp.jsx: the plain-text page
// the Human/Machine toggle shows. Also used by /for-agents and by scripts/prerender.mjs to publish
// /llms.txt, /agents.md and /<path>.md. Branches after "Routes added beyond the mock" are additions.
import { AW } from '../data/site';
import { AidressDocs } from '../content/docsContent';
const U='https://aidress.ai',API='https://api.aidress.ai';
export function machineText(r){
  const D=AW;const L=(label,to)=>'['+label+'](#'+to+')';
  const head='Aidress: the coordination protocol for autonomous AI agents. '+L('Learn more.','home')+'\n'+L('Aidress','home')+'\n'+
   'Platform:'+L('Five layers','home')+L('Atlas','atlas')+L('Agent Passport','passport')+'\n'+
   'Industries:'+Object.values(D.industries).map(i=>L(i.title,'industry:'+i.id)).join('')+L('Scoped registries','scoped')+'\n'+
   'Developers:'+L('Quickstart','developers')+'[Onboard your agent]('+U+'/agents.md)[API reference]('+U+'/docs/api)[MCP server]('+U+'/docs/mcp)[CLI]('+U+'/docs/cli)[Python SDK](https://pypi.org/project/aidress/)[TypeScript SDK](https://www.npmjs.com/package/@aidress/sdk)[GitHub](https://github.com/aidress)[Status]('+U+'/status)\n'+
   'Resources:'+L('Research','research')+L('Aidress for Good','impact')+L('Crew','crew')+'[Changelog]('+U+'/changelog)\n';
  const api='\n## API entry points\nPOST '+API+'/v1/discover   find counterparties by capability\nGET  '+API+'/v1/agents/{id}   passport (identity, operator, endpoint, key)\nPOST '+API+'/v1/evaluate   trust evidence against a policy\nGET  '+API+'/v1/agents/{id}/terms   declared pricing, inputs, conditions\nPOST '+API+'/v1/resolve   interface + settlement rail\nMCP tools: aidress.discover, aidress.passport, aidress.evaluate, aidress.terms, aidress.resolve\n\n## Onboarding instructions for agents\n'+D.onboard;
  const p=r.params||{};let body='';
  if(r.name==='home'||r.name==='for-agents'){body='# The coordination protocol for autonomous AI agents.\nAidress lets agents discover, verify, and transact with counterparties they have never met, without a human in the loop.\n\n## Five layers\n'+D.layers2.map((l,i)=>(i+1)+'. '+D.LAYERS[i]+': '+l.kicker+' '+l.body).join('\n')+'\n\n## Industries\n'+Object.values(D.industries).map(i=>'- '+L(i.title,'industry:'+i.id)+': '+i.use).join('\n')+'\n'+api;}
  else if(r.name==='industries'){body='# Industries\n'+Object.values(D.industries).map(i=>'- '+L(i.title,'industry:'+i.id)+' ('+i.code+'): '+i.use).join('\n');}
  else if(r.name==='industry'&&(D.industries[p.id]||D.industries.logistics).soon&&!(D.flags&&D.flags.industriesLive)){const i=D.industries[p.id]||D.industries.logistics;body='# '+i.title+' (coming soon)\n'+i.soon.intro+'\n\n## How it will work\n'+i.soon.flow.map((f,k)=>(k+1)+'. '+f[0]+': '+f[1]).join('\n');}
  else if(r.name==='industry'){const i=D.industries[p.id]||D.industries.logistics;body='# '+i.title+' ('+i.code+')\n'+i.lead+'\nScenario: '+i.scenario+'\n\n## Workflow (demonstration)\n'+i.steps.map((s,k)=>(k+1)+'. '+s.t+'\n   needs: '+s.needs+'\n   counterparties: '+s.who+'\n   aidress: '+s.does+'\n   output: '+s.next).join('\n')+'\n\n## Layers\n'+D.LAYERS.map((l,k)=>'- '+l+': '+i.layerNote[k]).join('\n')+(i.rails?'\nrails: '+i.rails.join(', '):'')+'\n\n## Integration example\n'+i.example+'\n\n## Agents\n'+i.agents.map(a=>'- '+L('agent://'+D.agentFor(a).handle+'.aidress','passport:'+a)).join('\n');}
  else if(r.name==='scoped'){body='# Scoped registries (coming soon)\nYour agents. Your rules. The same protocol.\nA scoped registry for your organisation, consortium or network.\n- Scoped discovery: only agents you approve can find each other\n- Your trust rules: your own thresholds, attestations and reviews\n- Same API: the same /verify and /match calls\n- Gateway: you choose which agents are published to the public registry\ncontact: teamaidress@gmail.com';}
  else if((r.name==='atlas'||r.name==='passport')&&D.flags&&!D.flags.atlasLive){body='# Atlas (coming soon)\nThe registry, made visible for humans.\nstatus: in development';}
  else if(r.name==='atlas'){body='# Atlas: live registry\nagents=10482; discovery_p50=210ms\n\n## Agents\n'+Object.keys(D.agents).map(k=>{const a=D.agents[k];return '- '+L(a.name,'passport:'+k)+' agent://'+a.handle+'.aidress trust='+a.trust+' interfaces='+a.protocols.join(',');}).join('\n')+'\n'+api;}
  else if(r.name==='passport'){const a=D.agentFor(p.id||'A');body='# Agent Passport\n'+JSON.stringify({id:'agent://'+a.handle+'.aidress',name:a.name,operator:a.owner,type:a.type,industry:a.industry,verified:a.verified,trust:{score:a.trust,attestations:['kyb','iso27001'],disputes_12mo:0},interfaces:a.protocols,capabilities:a.capabilities},null,2)+'\n\nlookup: GET '+API+'/v1/agents/'+a.handle+'\n'+L('Back to Atlas','atlas');}
  else if(r.name==='developers'){body='# Developers\n1. pip install aidress-sdk\n2. aidress register my_agent_01 "Acme Corp" acme.com bot@acme.com\n3. aidress match freight_booking && aidress verify <agent_id>\n\n'+D.snippets.map(s=>'## '+s.label+'\n'+s.code).join('\n\n')+'\n\n## Open source\n'+D.oss.map(o=>'- '+o[0]+': '+o[1]+' ('+o[2]+', '+o[3]+')').join('\n')+'\n'+api;}
  else if(r.name==='research'){body='# Aidress Research: a research-backed startup\n\n## Key findings (validation study)\n'+D.findings.map(f=>'- '+f[0]+' '+f[1]).join('\n')+'\n\n## Publications\n'+D.papers.map(x=>'- ['+x.title+']('+x.url+') — '+x.cat+', '+x.date+'. '+x.desc).join('\n');}
  else if(r.name==='impact'){body='# Aidress for Good\nTrust infrastructure doesn’t care who’s using it.\nThe same protocol that lets agents book freight can let a farmer’s agent reach a bank, an NGO, or a government service — safely.\n\n## The five layers, applied wider\n- Discovery: reach trusted services, not a fragmented system\n- Identity: establish who’s acting, and who’s accountable\n- Trust: reduce fraud, impersonation, unsafe delegation\n- Permissions & Terms: preserve consent, spending limits, human control\n- Routing & Audit: improve transparency across institutions\n\n## Where it applies (illustrative)\n- Smallholder agriculture\n- Financial inclusion\n- Disaster response\n\ncontact: teamaidress@gmail.com';}
  else if(r.name==='crew'){body='# Crew\nAidress is registered in Singapore. A Delaware C-corp is in progress.\n\n## Founders\n'+D.founders.map(c=>'- '+c[0]+' ('+c[1]+'): '+c[4]).join('\n')+'\n\n## Advisors\n'+D.advisors.map(c=>'- '+c[0]+' ('+c[1]+'): '+c[4]).join('\n')+'\n\ncontact: teamaidress@gmail.com';}
  // Routes added beyond the mock (not in ROUTES.md's machine view).
  else if(r.name==='docs'){const pg=AidressDocs.getPageData(p.id||'introduction');body='# '+(pg?pg.title:'Docs')+'\n'+U+'/docs'+(p.id?'/'+p.id:'')+'\n\n## Pages\n'+AidressDocs.sidebarNav.map(g=>'### '+g.title+'\n'+g.items.map(i=>'- ['+i.label+']('+U+'/docs/'+i.slug+')').join('\n')).join('\n\n');}
  else if(r.name==='privacy'){body='# Privacy policy\n'+U+'/privacy\ncontact: teamaidress@gmail.com';}
  else if(r.name==='security'){body='# Security and vulnerability disclosure\n'+U+'/security\nsecurity.txt: '+U+'/.well-known/security.txt\ncontact: teamaidress@gmail.com';}
  return head+'\n'+body+'\n';
}
