// @ts-nocheck — line-for-line port of the untyped design mock; see design_handoff_aidress_website.
/* eslint-disable react-refresh/only-export-components, react-hooks/exhaustive-deps, react-hooks/rules-of-hooks */
// Docs portal, ported from design_handoff_aidress_website/design/ui_kits/website/Docs.jsx.
import React from 'react';
import { hrefFor, spaClick } from '../lib/routes';
import { Icon } from '../components/ds';
import { AidressDocs } from '../content/docsContent';
const mono={font:'400 12px/1 var(--font-mono)',textTransform:'uppercase',letterSpacing:'0.02em'};
const V='#E84A27',INK='#212320';
const DOC_TABS=[{id:'start',label:'Get started',icon:'book-open',groups:['Getting Started','Help']},{id:'concepts',label:'Concepts',icon:'layers',groups:['Core Concepts']},{id:'sdks',label:'SDKs & tools',icon:'terminal',groups:['SDKs & Integrations']},{id:'api',label:'API reference',icon:'code',groups:['API Reference']},{id:'ref',label:'Reference',icon:'file-text',groups:['Reference']}];
const DOC_ICON={interoperability:'route',introduction:'book-open',quickstart:'arrow-right',authentication:'key-round',faq:'list','trust-scores':'shield-check','anti-gaming':'lock','capability-resolution':'network',payments:'credit-card','org-api-keys':'key-round','python-sdk':'code',cli:'terminal','mcp-server':'cpu',langchain:'layers',strands:'route','error-codes':'activity','a2a-compatibility':'globe',standards:'file-text',changelog:'refresh-cw'};
const START=[['quickstart','Quickstart','Verify your first agent in under 60 seconds.','arrow-right'],['authentication','Authentication','Bearer keys and Ed25519 signatures.','key-round'],['mcp-server','MCP server','Connect Claude, Cursor or any MCP client.','cpu'],['verify','API reference','Every endpoint, request and response.','code']];
function Method({label}){const m=label.match(/^(GET|POST)\s+(.*)$/);if(!m)return null;return <span style={{display:'inline-flex',alignItems:'center',gap:8,minWidth:0}}><span style={{flex:'none',font:'500 9.5px/1 var(--font-mono)',padding:'3px 4px',minWidth:30,textAlign:'center',border:'1px solid '+(m[1]==='GET'?'var(--border-box)':'#E84A27'),color:m[1]==='GET'?'#3a3c38':'#B8381C'}}>{m[1]}</span><span style={{font:'400 12.5px/1.25 var(--font-mono)',overflow:'hidden',textOverflow:'ellipsis'}}>{m[2]}</span></span>;}
function Docs({go,params}){
  const DD=AidressDocs;const slug=(params&&params.id)||'introduction';
  const page=DD.getPageData(slug)||DD.getPageData('introduction');
  const [narrow,setNarrow]=React.useState(()=>typeof matchMedia!=='undefined'&&matchMedia('(max-width: 900px)').matches);React.useEffect(()=>{const m=matchMedia('(max-width: 900px)');const f=()=>setNarrow(m.matches);m.addEventListener('change',f);return()=>m.removeEventListener('change',f);},[]);
  const [navOpen,setNavOpen]=React.useState(false);const [q,setQ]=React.useState('');const [spy,setSpy]=React.useState(null);const [copied,setCopied]=React.useState(false);
  const artRef=React.useRef();
  React.useEffect(()=>{window.scrollTo(0,0);setSpy(page.anchors[0]&&page.anchors[0].id);},[slug]);
  React.useEffect(()=>{const els=page.anchors.map(x=>document.getElementById(x.id)).filter(Boolean);if(!els.length)return;const io=new IntersectionObserver(es=>{const v=es.filter(e=>e.isIntersecting).sort((x,y)=>x.boundingClientRect.top-y.boundingClientRect.top)[0];if(v)setSpy(v.target.id);},{rootMargin:'-80px 0px -65% 0px'});els.forEach(e=>io.observe(e));return()=>io.disconnect();},[slug]);
  const groupOf=s=>DD.sidebarNav.find(g=>g.items.some(i=>i.slug===s));
  const tab=DOC_TABS.find(t=>t.groups.includes((groupOf(slug)||{}).title))||DOC_TABS[0];
  const flat=DD.sidebarNav.flatMap(g=>g.items);const ix=flat.findIndex(x=>x.slug===slug);const prev=flat[ix-1],next=flat[ix+1];
  const jump=id=>{const el=document.getElementById(id);el&&window.scrollTo({top:el.getBoundingClientRect().top+window.scrollY-80,behavior:'smooth'});};
  const isEp=l=>/^(GET|POST)/.test(l);
  const groups=q?DD.sidebarNav.map(g=>({...g,items:g.items.filter(i=>i.label.toLowerCase().includes(q.toLowerCase()))})).filter(g=>g.items.length):DD.sidebarNav.filter(g=>tab.groups.includes(g.title));
  const navList=<div style={{display:'flex',flexDirection:'column',gap:20}}>
    <label style={{display:'flex',alignItems:'center',gap:8,padding:'8px 10px',border:'1px solid var(--border-box)',background:'var(--paper)'}}><Icon name="search" size={14} color="#6b6d66"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter pages" style={{all:'unset',flex:1,minWidth:0,font:'400 13.5px/1.2 var(--font-sans)'}}/>{q&&<button onClick={()=>setQ('')} style={{all:'unset',cursor:'pointer',display:'flex'}}><Icon name="x" size={13}/></button>}</label>
    {groups.map(g=><div key={g.title} style={{display:'flex',flexDirection:'column',gap:1}}>
    <div style={{...mono,fontSize:10.5,color:'var(--text-secondary)',margin:'0 0 8px'}}>{g.title}</div>
    {g.items.map(it=>{const on=it.slug===slug;return <a key={it.slug} href={hrefFor('docs:'+it.slug)} onClick={spaClick(()=>{setNavOpen(false);setQ('');go('docs:'+it.slug);})} style={{cursor:'pointer',display:'flex',alignItems:'center',gap:10,padding:'7px 10px',marginLeft:-10,background:on?'#F5F1EA':'transparent',borderLeft:'2px solid '+(on?V:'transparent'),font:'400 14px/1.25 var(--font-sans)',color:on?INK:'#3a3c38',fontWeight:on?500:400}}>{isEp(it.label)?<Method label={it.label}/>:<><Icon name={DOC_ICON[it.slug]||'file-text'} size={15} color={on||it.featured?V:'#6b6d66'}/><span style={{flex:1,minWidth:0}}>{it.label}</span>{it.featured&&<span style={{flex:'none',font:'500 9.5px/1 var(--font-mono)',textTransform:'uppercase',padding:'3px 5px',background:V,color:INK}}>Core</span>}</>}</a>;})}
  </div>)}{q&&!groups.length&&<span style={{font:'400 13.5px/1.4 var(--font-sans)',color:'var(--text-secondary)'}}>No pages match “{q}”.</span>}</div>;
  const tabs=<div style={{display:'flex',gap:2,overflowX:'auto',scrollbarWidth:'none',padding:'0 var(--gutter)',borderBottom:'1px solid var(--border-subtle)',background:'var(--paper)',position:'sticky',top:64,zIndex:5}}>
    {DOC_TABS.map(t=>{const on=t.id===tab.id;const first=DD.sidebarNav.find(g=>g.title===t.groups[0]).items[0].slug;return <a key={t.id} href={hrefFor('docs:'+first)} onClick={spaClick(()=>{setQ('');go('docs:'+first);})} style={{cursor:'pointer',flex:'none',display:'flex',alignItems:'center',gap:8,padding:'14px 14px 12px',borderBottom:'2px solid '+(on?V:'transparent'),font:'400 14px/1 var(--font-sans)',color:on?INK:'#5a5c56',fontWeight:on?500:400}}><Icon name={t.icon} size={15} color={on?V:'currentColor'}/>{t.label}</a>;})}
    <span style={{flex:1}}></span>
    {!narrow&&<a href="https://aidress.ai/llms.txt" target="_blank" rel="noopener" style={{flex:'none',display:'flex',alignItems:'center',gap:6,padding:'14px 0 12px',...mono,fontSize:11,color:'#5a5c56'}}>llms.txt <Icon name="arrow-up-right" size={12}/></a>}
  </div>;
  const copyPage=()=>{const t=artRef.current?artRef.current.innerText:'';navigator.clipboard&&navigator.clipboard.writeText(t);setCopied(true);setTimeout(()=>setCopied(false),1500);};
  return <div className="ad-docs" style={{'--docs-accent':'#B8381C','--docs-heading':INK,'--docs-body':'#3a3c38','--docs-faint':'#6b6d66','--docs-border':'var(--border-subtle)','--docs-code-bg':'var(--stone-100)','--docs-callout-bg':'#F5F1EA',background:'var(--paper)'}}>
    {tabs}
    <div style={{display:'grid',gridTemplateColumns:narrow?'minmax(0,1fr)':'260px minmax(0,1fr) 210px'}}>
    {!narrow&&<aside style={{position:'sticky',top:112,alignSelf:'start',maxHeight:'calc(100vh - 112px)',overflowY:'auto',padding:'24px 20px 40px var(--gutter)',borderRight:'1px solid var(--border-subtle)',boxSizing:'border-box'}}>{navList}</aside>}
    <article style={{padding:narrow?'24px var(--gutter) 64px':'36px 56px 80px',maxWidth:820,minWidth:0,boxSizing:'border-box'}}>
      {narrow&&<button onClick={()=>setNavOpen(!navOpen)} style={{all:'unset',cursor:'pointer',display:'flex',justifyContent:'space-between',alignItems:'center',width:'100%',boxSizing:'border-box',padding:'12px 14px',border:'1px solid var(--border-box)',marginBottom:24,...mono,fontSize:11}}><span style={{display:'flex',gap:8,alignItems:'center'}}><Icon name="list" size={14}/>{tab.label} · {page.title}</span><Icon name={navOpen?'x':'chevron-down'} size={14}/></button>}
      {narrow&&navOpen&&<div style={{marginBottom:28,paddingBottom:24,borderBottom:'1px solid var(--border-rule)'}}>{navList}</div>}
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}>
        <div style={{display:'flex',alignItems:'center',gap:6,...mono,fontSize:11,color:'var(--text-secondary)'}}><a href={hrefFor('docs')} onClick={spaClick(()=>go('docs'))} style={{cursor:'pointer'}}>Docs</a><Icon name="chevron-right" size={12}/><span>{page.breadcrumb}</span></div>
        <button onClick={copyPage} style={{all:'unset',cursor:'pointer',display:'flex',alignItems:'center',gap:6,padding:'6px 9px',border:'1px solid var(--border-box)',...mono,fontSize:10.5,color:copied?'#B8381C':INK}}><Icon name={copied?'check':'copy'} size={12}/>{copied?'Copied':'Copy page'}</button>
      </div>
      <h1 style={{margin:'18px 0 8px',font:(isEp(page.title)?'400 clamp(26px,4vw,40px)/1.1 var(--font-mono)':'500 clamp(34px,5vw,52px)/1 var(--font-sans)'),letterSpacing:isEp(page.title)?'-0.01em':'-0.045em',color:INK}}>{page.title}</h1>
      {slug==='introduction'&&<a href={hrefFor('docs:interoperability')} onClick={spaClick(()=>go('docs:interoperability'))} className="ad-doc-dark" style={{cursor:'pointer',display:'flex',gap:18,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap',margin:'24px 0 0',padding:'20px 22px',background:INK,color:'#F5F4EF',border:'1px solid '+INK}}><span style={{display:'flex',flexDirection:'column',gap:8,minWidth:0}}><span style={{display:'flex',alignItems:'center',gap:8,font:'400 11px/1 var(--font-mono)',textTransform:'uppercase',color:'#F07A5C'}}><span style={{width:7,height:7,background:V}}></span>Core concept · Interoperability Layer</span><span style={{font:'500 22px/1.15 var(--font-sans)',letterSpacing:'-0.02em'}}>One call. Any agent. Any protocol.</span></span><span style={{display:'flex',alignItems:'center',gap:8,font:'400 12px/1 var(--font-mono)',textTransform:'uppercase',padding:'10px 12px',background:V,color:INK}}>Read <Icon name="arrow-right" size={13}/></span></a>}
      {slug==='introduction'&&<div style={{display:'grid',gridTemplateColumns:narrow?'1fr':'repeat(2,minmax(0,1fr))',gap:12,margin:'24px 0 8px'}}>{START.map(([s,t,dsc,ic])=><a key={s} href={hrefFor('docs:'+s)} onClick={spaClick(()=>go('docs:'+s))} className="ad-doc-card" style={{cursor:'pointer',display:'flex',gap:14,alignItems:'flex-start',padding:'16px 18px',border:'1px solid var(--border-box)',background:'var(--paper)'}}><span style={{flex:'none',width:32,height:32,display:'flex',alignItems:'center',justifyContent:'center',background:'#F5F1EA',color:V}}><Icon name={ic} size={16}/></span><span style={{display:'flex',flexDirection:'column',gap:4,minWidth:0}}><span style={{font:'500 15.5px/1.2 var(--font-sans)'}}>{t}</span><span style={{font:'400 13.5px/1.4 var(--font-sans)',color:'#5a5c56'}}>{dsc}</span></span></a>)}</div>}
      <div ref={artRef}>{page.content}</div>
      <div style={{marginTop:56,paddingTop:24,borderTop:'1px solid var(--border-rule)',display:'grid',gridTemplateColumns:narrow?'1fr':'repeat(3,minmax(0,1fr))',gap:12}}>
        {[['Discord','Chat with our devs for support and errors.','https://discord.gg/DG2VjeB7T','globe'],['Changelog','What’s new in the API, SDK and CLI.',null,'refresh-cw'],['llms.txt','The docs, machine-readable.','https://aidress.ai/llms.txt','file-text']].map(([t,dsc,u,ic])=><a key={t} href={u||hrefFor('docs:changelog')} target={u?'_blank':undefined} rel="noopener" onClick={u?undefined:spaClick(()=>go('docs:changelog'))} className="ad-doc-card" style={{cursor:'pointer',display:'flex',flexDirection:'column',gap:6,padding:'14px 16px',border:'1px solid var(--border-subtle)'}}><span style={{display:'flex',alignItems:'center',gap:8,font:'500 14.5px/1.2 var(--font-sans)'}}><Icon name={ic} size={14} color={V}/>{t}</span><span style={{font:'400 13px/1.4 var(--font-sans)',color:'#5a5c56'}}>{dsc}</span></a>)}
      </div>
      <div style={{marginTop:16,display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>
        {prev?<a href={hrefFor('docs:'+prev.slug)} onClick={spaClick(()=>go('docs:'+prev.slug))} className="ad-doc-card" style={{cursor:'pointer',padding:'14px 16px',border:'1px solid var(--border-box)',display:'flex',flexDirection:'column',gap:6}}><span style={{display:'flex',alignItems:'center',gap:4,...mono,fontSize:10.5,color:'var(--text-secondary)'}}><Icon name="arrow-left" size={12}/>Previous</span><span style={{font:'500 15px/1.2 var(--font-sans)'}}>{prev.label}</span></a>:<span></span>}
        {next&&<a href={hrefFor('docs:'+next.slug)} onClick={spaClick(()=>go('docs:'+next.slug))} className="ad-doc-card" style={{cursor:'pointer',padding:'14px 16px',border:'1px solid var(--border-box)',display:'flex',flexDirection:'column',gap:6,alignItems:'flex-end',textAlign:'right'}}><span style={{display:'flex',alignItems:'center',gap:4,...mono,fontSize:10.5,color:'var(--text-secondary)'}}>Next<Icon name="arrow-right" size={12}/></span><span style={{font:'500 15px/1.2 var(--font-sans)'}}>{next.label}</span></a>}
      </div>
    </article>
    {!narrow&&<nav style={{position:'sticky',top:112,alignSelf:'start',padding:'36px var(--gutter) 40px 0',display:'flex',flexDirection:'column',gap:2}}>{page.anchors.length>0&&<><span style={{...mono,fontSize:10.5,color:'var(--text-secondary)',marginBottom:10}}>On this page</span>{page.anchors.map(x=>{const on=spy===x.id;return <a key={x.id} href={'#'+x.id} onClick={spaClick(()=>jump(x.id))} style={{cursor:'pointer',padding:'5px 0 5px 12px',borderLeft:'2px solid '+(on?V:'var(--border-subtle)'),font:'400 13.5px/1.3 var(--font-sans)',color:on?INK:'#5a5c56',fontWeight:on?500:400,transition:'color var(--dur-fast), border-color var(--dur-fast)'}}>{x.label}</a>;})}</>}</nav>}
    </div>
  </div>;
}
export { Docs };
