// @ts-nocheck — line-for-line port of the untyped design mock; see design_handoff_aidress_website.
// Docs typography and blocks, ported from design_handoff_aidress_website/design/ui_kits/website/docsContent.jsx
// (lines 3–20, window.AidressDocs.ui in the mock). Styles are verbatim.
/* eslint-disable react-refresh/only-export-components */
import React from 'react';
import { globalGo } from '../lib/routes';
const MONO="var(--font-mono)";
function Link({to,children,style,className}){const go=()=>{const g=globalGo;if(to.startsWith('/docs')){const s=to.replace(/^\/docs\/?/,'').split('#')[0]||'introduction';g?g('docs:'+s):0;}else if(to==='/'){g&&g('home');}else window.open('https://aidress.ai'+to,'_blank');};return <a onClick={go} className={className} style={{cursor:'pointer',...style}}>{children}</a>;}
function CodeBlock({lang,children}){const [k,setK]=React.useState(false);return <div style={{margin:'16px 0',background:'#212320',color:'#F5F4EF',border:'1px solid #212320'}}><div style={{display:'flex',justifyContent:'space-between',padding:'8px 14px',borderBottom:'1px solid #3a3c38',font:'400 11px/1 '+MONO,textTransform:'uppercase',color:'#9a9c95'}}><span>{lang||'text'}</span><button onClick={()=>{navigator.clipboard&&navigator.clipboard.writeText(children);setK(true);setTimeout(()=>setK(false),1500);}} style={{all:'unset',cursor:'pointer',color:k?'#f29a7f':'#9a9c95'}}>{k?'Copied':'Copy'}</button></div><pre style={{margin:0,padding:'14px 16px',font:'400 13px/1.6 '+MONO,overflowX:'auto',whiteSpace:'pre'}}>{children}</pre></div>;}
function InlineCode({children}){return <code style={{font:'400 0.88em/1 '+MONO,color:'var(--docs-accent)',background:'var(--docs-callout-bg)',padding:'2px 5px'}}>{children}</code>;}
function Callout({type,children}){const lab={info:'Info',warning:'Warning',tip:'Tip'}[type];return <div style={{margin:'20px 0',padding:'14px 18px',border:'1px solid '+(type==='warning'?'#212320':'var(--docs-accent)'),background:'var(--docs-callout-bg)'}}><div style={{font:'400 11px/1 '+MONO,textTransform:'uppercase',color:type==='warning'?'#212320':'var(--docs-accent)',marginBottom:8}}>{lab}</div><div style={{font:'400 15px/1.6 var(--font-sans)',color:'var(--docs-body)'}}>{children}</div></div>;}
const th={textAlign:'left',padding:'9px 14px 9px 0',font:'400 11px/1.2 '+MONO,textTransform:'uppercase',color:'var(--docs-faint)',borderBottom:'1px solid #212320'};
const td={padding:'11px 14px 11px 0',font:'400 14px/1.45 var(--font-sans)',color:'var(--docs-body)',borderBottom:'1px solid var(--docs-border)',verticalAlign:'top'};
function TableScroll({children}){return <div style={{margin:'16px 0',overflowX:'auto',WebkitOverflowScrolling:'touch'}}>{children}</div>;}
function ParamTable({params}){return <TableScroll><table style={{width:'100%',minWidth:480,borderCollapse:'collapse'}}><thead><tr><th style={th}>Name</th><th style={th}>Type</th><th style={th}>Required</th><th style={th}>Description</th></tr></thead><tbody>{params.map(p=>{const req=p.required===true||p.required==='Yes';return <tr key={p.name}><td style={td}><InlineCode>{p.name}</InlineCode></td><td style={{...td,font:'400 13px/1.45 '+MONO}}>{p.type}</td><td style={{...td,color:req?'var(--docs-accent)':'var(--docs-faint)'}}>{req?'Yes':typeof p.required==='string'?p.required:'No'}</td><td style={td}>{p.description}</td></tr>;})}</tbody></table></TableScroll>;}
function SimpleTable({headers,rows}){return <TableScroll><table style={{width:'100%',minWidth:380,borderCollapse:'collapse'}}><thead><tr>{headers.map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} style={td}>{c}</td>)}</tr>)}</tbody></table></TableScroll>;}
function Badge({label,color}){return <span style={{display:'inline-flex',alignItems:'center',gap:6,font:'400 11px/1 '+MONO,textTransform:'uppercase',color:color==='green'?'#212320':'var(--docs-faint)'}}>{color==='green'&&<span style={{width:7,height:7,background:'#E84A27'}}></span>}{label}</span>;}
function StatusBadge({code}){const n=Number(code);return <span style={{font:'500 12px/1 '+MONO,padding:'3px 6px',border:'1px solid '+(n<300?'#E84A27':'#212320'),color:n<300?'var(--docs-accent)':'#212320'}}>{code}</span>;}
function H2({id,children}){return <h2 id={id} style={{margin:'44px 0 0',paddingTop:28,borderTop:'1px solid var(--docs-border)',font:'500 26px/1.15 var(--font-sans)',letterSpacing:'-0.025em',color:'var(--docs-heading)',scrollMarginTop:90}}>{children}</h2>;}
function H3({id,children}){return <h3 id={id} style={{margin:'26px 0 0',font:'500 18px/1.25 var(--font-sans)',color:'var(--docs-heading)',scrollMarginTop:90}}>{children}</h3>;}
function P({children,style}){return <p style={{margin:'12px 0 0',font:'400 16px/1.65 var(--font-sans)',color:'var(--docs-body)',textWrap:'pretty',...style}}>{children}</p>;}
const CHANGE_TAG={feature:'New',improvement:'Improved',fix:'Fix',breaking:'Breaking'};
function ChangeEntry({version,tags,title,children}){return <div><div style={{display:'flex',flexWrap:'wrap',gap:12,font:'400 11px/1 '+MONO,textTransform:'uppercase'}}>{version&&<span style={{color:'var(--docs-accent)'}}>{version}</span>}{tags.map(x=><span key={x} style={{color:x==='breaking'?'#212320':'var(--docs-faint)',fontWeight:x==='breaking'?600:400}}>{CHANGE_TAG[x]}</span>)}</div><h3 style={{margin:'10px 0 0',font:'500 20px/1.25 var(--font-sans)',color:'var(--docs-heading)'}}>{title}</h3><div style={{marginTop:10,font:'400 15px/1.6 var(--font-sans)',color:'var(--docs-body)'}}>{children}</div></div>;}
function Timeline({data}){return <div className="ad-tl" style={{marginTop:28,borderTop:'1px solid var(--docs-border)'}}>{data.map((d,i)=><div key={i} className="ad-tl-row" style={{display:'grid',gridTemplateColumns:'150px minmax(0,1fr)',gap:24,padding:'28px 0',borderBottom:'1px solid var(--docs-border)'}}><div style={{font:'400 12px/1.3 '+MONO,textTransform:'uppercase',color:'var(--docs-faint)'}}>{d.title}</div><div>{d.content}</div></div>)}</div>;}

export { P,H2,H3,CodeBlock,InlineCode,Callout,SimpleTable,ParamTable,Badge,StatusBadge,Link,ChangeEntry,Timeline,TableScroll,MONO,th,td,CHANGE_TAG };
