(()=>{
const SITE={home:'main',industries:'main',industry:'main',scoped:'main',crew:'main',developers:'main',docs:'main',impact:'main',atlas:'atlas',passport:'atlas',research:'research'};
const MAIN_LINKS=['Platform','Industries','Developers','Research','Company'];
const MAIN_TO={Platform:'home',Industries:'industries',Developers:'developers',Research:'research',Company:'crew'};
const docSlug=re=>{try{for(const g of window.AidressDocs.sidebarNav)for(const i of g.items)if(re.test(i.label))return 'docs:'+i.slug;}catch(e){}return 'docs';};
const MENUS=()=>({Platform:[['Five layers','home'],['Atlas','atlas']],Developers:[['Overview','developers'],['Docs','docs'],['Quickstart',docSlug(/quick/i)],['API reference',docSlug(/api/i)],['MCP server',docSlug(/mcp/i)],['GitHub ↗','ext:https://github.com/Aidress-ai/Aidress']],Company:[['Aidress for Good','impact'],['Crew','crew'],['Contact','ext:mailto:teamaidress@gmail.com']]});
const nav=(go,k)=>{if(k.startsWith('ext:')){window.open(k.slice(4),'_blank');return;}go(MAIN_TO[k]||k);};
const U='https://aidress.ai',API='https://api.aidress.ai';
function machineText(r){
  const D=window.AW;const L=(label,to)=>'['+label+'](#'+to+')';
  const head='Aidress: the coordination protocol for autonomous AI agents. '+L('Learn more.','home')+'\n'+L('Aidress','home')+'\n'+
   'Platform:'+L('Five layers','home')+L('Atlas','atlas')+L('Agent Passport','passport')+'\n'+
   'Industries:'+Object.values(D.industries).map(i=>L(i.title,'industry:'+i.id)).join('')+L('Scoped registries','scoped')+'\n'+
   'Developers:'+L('Quickstart','developers')+'[Onboard your agent]('+U+'/agents.md)[API reference]('+U+'/docs/api)[MCP server]('+U+'/docs/mcp)[CLI]('+U+'/docs/cli)[Python SDK](https://pypi.org/project/aidress/)[TypeScript SDK](https://www.npmjs.com/package/@aidress/sdk)[GitHub](https://github.com/aidress)[Status]('+U+'/status)\n'+
   'Resources:'+L('Research','research')+L('Aidress for Good','impact')+L('Crew','crew')+'[Changelog]('+U+'/changelog)\n';
  const api='\n## API entry points\nPOST '+API+'/v1/discover   find counterparties by capability\nGET  '+API+'/v1/agents/{id}   passport (identity, operator, endpoint, key)\nPOST '+API+'/v1/evaluate   trust evidence against a policy\nGET  '+API+'/v1/agents/{id}/terms   declared pricing, inputs, conditions\nPOST '+API+'/v1/resolve   interface + settlement rail\nMCP tools: aidress.discover, aidress.passport, aidress.evaluate, aidress.terms, aidress.resolve\n\n## Onboarding instructions for agents\n'+D.onboard;
  const p=r.params||{};let body='';
  if(r.name==='home'){body='# The coordination protocol for autonomous AI agents.\nAidress lets agents discover, verify, and transact with counterparties they have never met, without a human in the loop.\n\n## Five layers\n'+D.layers2.map((l,i)=>(i+1)+'. '+D.LAYERS[i]+': '+l.kicker+' '+l.body).join('\n')+'\n\n## Industries\n'+Object.values(D.industries).map(i=>'- '+L(i.title,'industry:'+i.id)+': '+i.use).join('\n')+'\n'+api;}
  else if(r.name==='industries'){body='# Industries\n'+Object.values(D.industries).map(i=>'- '+L(i.title,'industry:'+i.id)+' ('+i.code+'): '+i.use).join('\n');}
  else if(r.name==='industry'&&(D.industries[p.id]||D.industries.logistics).soon&&!(D.flags&&D.flags.industriesLive)){const i=D.industries[p.id]||D.industries.logistics;body='# '+i.title+' (coming soon)\n'+i.soon.intro+'\n\n## How it will work\n'+i.soon.flow.map((f,k)=>(k+1)+'. '+f[0]+': '+f[1]).join('\n');}
  else if(r.name==='industry'){const i=D.industries[p.id]||D.industries.logistics;body='# '+i.title+' ('+i.code+')\n'+i.lead+'\nScenario: '+i.scenario+'\n\n## Workflow (demonstration)\n'+i.steps.map((s,k)=>(k+1)+'. '+s.t+'\n   needs: '+s.needs+'\n   counterparties: '+s.who+'\n   aidress: '+s.does+'\n   output: '+s.next).join('\n')+'\n\n## Layers\n'+D.LAYERS.map((l,k)=>'- '+l+': '+i.layerNote[k]).join('\n')+(i.rails?'\nrails: '+i.rails.join(', '):'')+'\n\n## Integration example\n'+i.example+'\n\n## Agents\n'+i.agents.map(a=>'- '+L('agent://'+D.agentFor(a).handle+'.aidress','passport:'+a)).join('\n');}
  else if(r.name==='scoped'){body='# Scoped registries (coming soon)\nYour agents. Your rules. The same protocol.\nA scoped registry for your organisation, consortium or network.\n- Scoped discovery: only agents you approve can find each other\n- Your trust rules: your own thresholds, attestations and reviews\n- Same API: the same /verify and /match calls\n- Gateway: you choose which agents are published to the public registry\ncontact: teamaidress@gmail.com';}
  else if((r.name==='atlas'||r.name==='passport')&&D.flags&&!D.flags.atlasLive){body='# Atlas (coming soon)\nThe registry, made visible for humans.\nstatus: in development';}
  else if(r.name==='atlas'){body='# Atlas: live registry\nagents=10482; discovery_p50=210ms\n\n## Agents\n'+Object.keys(D.agents).map(k=>{const a=D.agents[k];return '- '+L(a.name,'passport:'+k)+' agent://'+a.handle+'.aidress trust='+a.trust+' interfaces='+a.protocols.join(',');}).join('\n')+'\n'+api;}
  else if(r.name==='passport'){const a=D.agentFor(p.id||'A');body='# Agent Passport\n'+JSON.stringify({id:'agent://'+a.handle+'.aidress',name:a.name,operator:a.owner,type:a.type,industry:a.industry,verified:a.verified,trust:{score:a.trust,attestations:['kyb','iso27001'],disputes_12mo:0},interfaces:a.protocols,capabilities:a.capabilities},null,2)+'\n\nlookup: GET '+API+'/v1/agents/'+a.handle+'\n'+L('Back to Atlas','atlas');}
  else if(r.name==='developers'){body='# Developers\n1. pip install aidress-sdk\n2. aidress register my_agent_01 "Acme Corp" acme.com bot@acme.com\n3. aidress match freight_booking && aidress verify <agent_id>\n\n'+D.snippets.map(s=>'## '+s.label+'\n'+s.code).join('\n\n')+'\n\n## Open source\n'+D.oss.map(o=>'- '+o[0]+': '+o[1]+' ('+o[2]+', '+o[3]+')').join('\n')+'\n'+api;}
  else if(r.name==='research'){body='# Aidress Research: a research-backed startup\n\n## Key findings (validation study)\n'+D.findings.map(f=>'- '+f[0]+' '+f[1]).join('\n')+'\n\n## Publications\n'+D.papers.map(x=>'- ['+x.title+']('+x.url+') — '+x.cat+', '+x.date+'. '+x.desc).join('\n');}
  else if(r.name==='impact'){body='# Aidress for Good\nTrust infrastructure doesn’t care who’s using it.\nThe same protocol that lets agents book freight can let a farmer’s agent reach a bank, an NGO, or a government service — safely.\n\n## The five layers, applied wider\n- Discovery: reach trusted services, not a fragmented system\n- Identity: establish who’s acting, and who’s accountable\n- Trust: reduce fraud, impersonation, unsafe delegation\n- Permissions & Terms: preserve consent, spending limits, human control\n- Routing & Audit: improve transparency across institutions\n\n## Where it applies (illustrative)\n- Smallholder agriculture\n- Financial inclusion\n- Disaster response\n\ncontact: teamaidress@gmail.com';}
  else if(r.name==='crew'){body='# Crew\nAidress is registered in Singapore. A Delaware C-corp is in progress.\n\n## Founders\n'+D.founders.map(c=>'- '+c[0]+' ('+c[1]+'): '+c[4]).join('\n')+'\n\n## Advisors\n'+D.advisors.map(c=>'- '+c[0]+' ('+c[1]+'): '+c[4]).join('\n')+'\n\ncontact: teamaidress@gmail.com';}
  return head+'\n'+body+'\n';
}
function GH({dark}){return <a href="https://github.com/Aidress-ai/Aidress" target="_blank" style={{font:'400 12px/1 var(--font-mono)',textTransform:'uppercase',color:dark?'var(--paper)':'var(--ink-deep)',border:'1px solid '+(dark?'#444':'var(--border-box)'),padding:'8px 10px',whiteSpace:'nowrap'}}>GitHub ↗</a>;}
const PAGES=[['Five layers','Platform','home'],['Atlas','Platform','atlas'],['Agent passport','Platform','passport'],['Developers','Developers','developers'],['Docs','Developers','docs'],['Research','Resources','research'],['Aidress for Good','Company','impact'],['Crew','Company','crew'],['Industries','Industries','industries'],['Scoped registries','Industries','scoped']];
function searchIndex(){const D=window.AW;return [...PAGES,...Object.values(D.industries).map(i=>[i.title,'Industry','industry:'+i.id]),...Object.keys(D.agents).map(k=>[D.agents[k].name+' · agent://'+D.agents[k].handle,'Agent','passport:'+k]),...['A2A','MCP','x402','HTTP'].map(p=>[p+' protocol','Protocol','docs']),...D.papers.map(p=>[p.title,'Research','research:'+p.id]),...window.AidressDocs.sidebarNav.flatMap(g=>g.items.map(i=>[i.label,'Docs · '+g.title,'docs:'+i.slug]))];}
function SiteSearch({go,onClose}){
  const {SearchInput}=window.AidressDesignSystem_f2dd6a;const [q,setQ]=React.useState('');
  const all=React.useMemo(searchIndex,[]);const res=(q?all.filter(r=>(r[0]+' '+r[1]).toLowerCase().includes(q.toLowerCase())):all.slice(0,8)).slice(0,8);
  React.useEffect(()=>{const k=e=>{if(e.key==='Escape')onClose();};addEventListener('keydown',k);setTimeout(()=>{const i=document.querySelector('#ad-search input');i&&i.focus();},30);return()=>removeEventListener('keydown',k);},[]);
  return <div onClick={onClose} style={{position:'fixed',inset:0,zIndex:100,background:'var(--overlay-scrim)',display:'flex',justifyContent:'center',alignItems:'flex-start',paddingTop:110}}>
    <div id="ad-search" onClick={e=>e.stopPropagation()} style={{width:'min(640px,92vw)',background:'var(--surface-card)',border:'1px solid var(--ink)',boxShadow:'0 20px 60px rgba(22,22,22,.18)'}}>
      <div style={{padding:12,borderBottom:'1px solid var(--border-subtle)'}}><SearchInput size="lg" value={q} onChange={setQ} placeholder="Search agents, industries, protocols or pages…"/></div>
      <div style={{maxHeight:380,overflowY:'auto'}}>{res.length?res.map(([l,c,to])=><a key={l+to} onClick={()=>{go(to);onClose();}} style={{display:'flex',justifyContent:'space-between',gap:16,padding:'12px 18px',cursor:'pointer',borderBottom:'1px solid var(--border-subtle)',font:'400 15px/1.3 var(--font-sans)'}}><span>{l}</span><span style={{font:'400 11px/1.3 var(--font-mono)',textTransform:'uppercase',color:'var(--text-secondary)'}}>{c}</span></a>):<div style={{padding:18,font:'400 14px/1.4 var(--font-sans)',color:'var(--text-secondary)'}}>No results for “{q}”.</div>}</div>
    </div></div>;
}
const pill=(dark)=>({all:'unset',cursor:'pointer',boxSizing:'border-box',display:'inline-flex',alignItems:'center',gap:8,height:34,padding:'0 10px',font:'400 12px/1 var(--font-mono)',textTransform:'uppercase',whiteSpace:'nowrap',color:dark?'var(--paper)':'var(--ink-deep)',border:'1px solid '+(dark?'#444':'var(--border-box)')});
function App(){
  const {NavBar,ModeToggle,MachineView}=window.AidressDesignSystem_f2dd6a;
  const init=(()=>{try{return JSON.parse(localStorage.getItem('aidress-site-route'))||{name:'home',params:{}}}catch(e){return {name:'home',params:{}}}})();
  const [route,setRoute]=React.useState(init);
  const [mode,setMode]=React.useState(()=>localStorage.getItem('aidress-site-mode')||'human');
  const go=(name,params={})=>{if(name.includes(':')){const [n,id]=name.split(':');name=n;params={id};}const r={name,params};setRoute(r);localStorage.setItem('aidress-site-route',JSON.stringify(r));window.scrollTo({top:0});};
  window.__adGo=go;
  const [theme,setTheme]=React.useState(()=>localStorage.getItem('aidress-site-theme')||'light');const [sOpen,setSOpen]=React.useState(false);const [menu,setMenu]=React.useState(false);
  
  React.useEffect(()=>{const k=e=>{if(e.key==='/'&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();setSOpen(true);}};addEventListener('keydown',k);return()=>removeEventListener('keydown',k);},[]);
  const setM=m=>{setMode(m);localStorage.setItem('aidress-site-mode',m);};
  const site=SITE[route.name]||'main';
  const S={home:window.Home,industries:window.Industries,industry:window.IndustryDetail,scoped:window.ScopedRegistries,crew:window.Crew,developers:window.Developers,docs:window.Docs,impact:window.Impact,atlas:window.AW.flags&&!window.AW.flags.atlasLive?window.AtlasSoon:window.Atlas,passport:window.AW.flags&&!window.AW.flags.atlasLive?window.AtlasSoon:window.Passport,research:window.Research}[route.name]||window.Home;
  const dark=site==='research'&&mode==='human';
  // Research is authored dark; every other page light. Invert whichever one disagrees with the saved theme so the mode is identical everywhere.
  React.useEffect(()=>{const inv=(theme==='dark')!==dark;document.documentElement.dataset.theme=inv?'dark':'light';try{localStorage.setItem('aidress-site-theme',theme);}catch(e){}},[theme,dark]);
  const {Icon}=window.AidressDesignSystem_f2dd6a;
  const extra=<div style={{display:'flex',gap:8,alignItems:'center'}}><button aria-label="Search" onClick={()=>setSOpen(true)} style={pill(dark)}><Icon name="search" size={14}/><span className="ad-hide-mobile">Search <span style={{opacity:.55}}>/</span></span></button><button aria-label="Toggle dark mode" onClick={()=>setTheme(theme==='dark'?'light':'dark')} style={pill(dark)}><span style={{width:10,height:10,borderRadius:'50%',border:'1.5px solid currentColor',background:theme==='dark'?'currentColor':'transparent',flex:'none'}}></span><span className="ad-hide-mobile">{theme==='dark'?'Light':'Dark'}</span></button><span className="ad-hide-mobile" style={{display:'contents'}}><ModeToggle value={mode} onChange={setM} tone={dark?'dark':'light'}/></span><button className="ad-mobile-only" aria-label="Menu" onClick={()=>setMenu(true)} style={pill(dark)}>Menu</button></div>;
  let header;
  if(site==='atlas') header=<NavBar logo={dark?'../../assets/logo-mark-paper.png':'../../assets/logo-mark-ink.png'} sticky sub="Atlas" links={['Network','Passports','Developers','aidress.ai ↗']} active={route.name==='passport'?'Passports':'Network'} onNavigate={l=>l==='aidress.ai ↗'?go('home'):l==='Developers'?go('developers'):l==='Passports'?go('passport',{id:'A'}):go('atlas')} onHome={()=>go('home')} extra={extra} search={false} cta="Register Agent" onCta={()=>go('developers')}/>;
  else if(site==='research') header=<NavBar logo={dark?'../../assets/logo-mark-paper.png':'../../assets/logo-mark-ink.png'} sticky tone={dark?'dark':'light'} sub="Research" links={['Publications','White paper','aidress.ai ↗']} active={route.params&&route.params.id==='whitepaper'?'White paper':'Publications'} onNavigate={l=>l==='aidress.ai ↗'?go('home'):l==='White paper'?go('research:whitepaper'):go('research')} onHome={()=>go('home')} extra={extra} search={false} cta={null}/>;
  else header=<NavBar logo={dark?'../../assets/logo-mark-paper.png':'../../assets/logo-mark-ink.png'} sticky links={MAIN_LINKS} active={{home:'Platform',industries:'Industries',industry:'Industries',scoped:'Industries',crew:'Company',developers:'Developers',docs:'Developers',impact:'Company'}[route.name]} menus={MENUS()} onNavigate={k=>nav(go,k)} onHome={()=>go('home')} extra={extra} search={false} cta="Connect agent" onCta={()=>go('developers')}/>;
  return <div style={{width:'100%',minHeight:'100vh',background:dark?'var(--ink-deep)':'var(--paper)'}}>
    {header}
    {mode==='machine'?<MachineView text={machineText(route)} onLink={to=>go(to)}/>:
    <main key={route.name+JSON.stringify(route.params)} style={{animation:'ad-fade-up var(--dur-slow) var(--ease-resolve)'}}><S go={go} params={route.params||{}}/></main>}
    {mode==='human'&&site!=='atlas'&&window.BigFooter&&<window.BigFooter go={go}/>}
    {menu&&<div style={{position:'fixed',inset:0,zIndex:120,background:'var(--paper)',display:'flex',flexDirection:'column',padding:'18px 20px 28px',overflowY:'auto'}}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',height:40}}><span style={{display:'flex',alignItems:'center',gap:10,font:'700 22px/1 var(--font-sans)',letterSpacing:'-0.035em'}}><img src="../../assets/logo-mark-ink.png" alt="" className="ad-noflip" style={{width:24,height:24,objectFit:'contain'}}/>AIDRESS</span><button onClick={()=>setMenu(false)} style={pill(false)}>Close</button></div>
      <nav style={{display:'flex',flexDirection:'column',marginTop:24,borderTop:'1px solid var(--border-rule)'}}>{MAIN_LINKS.map(x=>{const it=MENUS()[x];return <div key={x} style={{padding:'16px 0',borderBottom:'1px solid var(--border-rule)'}}><a onClick={()=>{setMenu(false);go(MAIN_TO[x]);}} style={{font:'500 26px/1 var(--font-sans)',letterSpacing:'-0.03em',cursor:'pointer'}}>{x}</a>{it&&<div style={{display:'flex',flexWrap:'wrap',gap:'8px 16px',marginTop:12}}>{it.map(([t,k])=><a key={t} onClick={()=>{setMenu(false);nav(go,k);}} style={{font:'400 14px/1.2 var(--font-sans)',color:'var(--text-secondary)',cursor:'pointer'}}>{t}</a>)}</div>}</div>;})}</nav>
      <div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:24}}><button onClick={()=>setTheme(theme==='dark'?'light':'dark')} style={pill(false)}>{theme==='dark'?'Light mode':'Dark mode'}</button><button onClick={()=>{setM(mode==='human'?'machine':'human');setMenu(false);}} style={pill(false)}>{mode==='human'?'Machine view':'Human view'}</button></div>
      <button onClick={()=>{setMenu(false);go('developers');}} style={{all:'unset',cursor:'pointer',marginTop:'auto',textAlign:'center',padding:'16px',background:'var(--vermilion-500)',color:'#fff',font:'500 17px/1 var(--font-sans)'}}>Connect agent</button>
    </div>}
    {sOpen&&<SiteSearch go={go} onClose={()=>setSOpen(false)}/>}
  </div>;
}
const NEED=['Home','Industries','IndustryDetail','Crew','Developers','Docs','Atlas','Passport','Research','Impact','BigFooter','FiveLayers'];
(function boot(n){if(window.__adBooted||!window.__adKitEntry)return;const DS=window.AidressDesignSystem_f2dd6a;if((DS&&DS.NavBar&&NEED.every(k=>window[k]))||n>400){window.__adBooted=true;ReactDOM.createRoot(document.getElementById('root')).render(<App/>);}else setTimeout(()=>boot(n+1),25);})(0);
})();
